spring:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  h2:
    console.enabled: true

  graphql:
    jpa:
      query:
        name: GraphQLJpaQueryStarwars
        description: GraphQL Jpa Query Starwars Schema Example
        enabled: true
